"""Stable semantic-transform exports; implementations belong to each format."""


from .rol_conversion_types import IdentityResolver, TransformResult
from .rol_mobiles import (
    MOB_ACTION_EXPANSIONS,
    MOB_ACTION_MAP,
    MOB_AFFECT2_MAP,
    MOB_AFFECT_MAP,
    MOB_AUTOMATIC_RACE_ACTION,
    MOB_AUTOMATIC_RACE_AFFECTS,
    MOB_DEFERRED_ACTIONS,
    MOB_SOURCE_ONLY_ACTIONS,
    MOB_SOURCE_ONLY_AFFECTS,
    MOB_SOURCE_RACE_IDENTITY_ACTIONS,
    MOB_SOURCE_VNUM_IDENTITY_ACTIONS,
    _manifest_bit,
    _mobile_conversion_inputs,
    _numeric_bitarray,
    emit_mobile,
    mobile_automatic_race_flags,
)
from .rol_objects import (
    APPLY_MAP,
    OBJECT_APPLY_DEFAULT_BONUS_TYPE,
    OBJECT_EXTRA_MAP,
    OBJECT_SOURCE_ONLY_AFFECTS,
    OBJECT_SOURCE_ONLY_APPLIES,
    OBJECT_SOURCE_ONLY_FLAGS,
    OBJECT_SOURCE_ONLY_WEAR_FLAGS,
    OBJECT_TYPE_MAP,
    OBJECT_WEAR_MAP,
    ROL_OBJECT_TRAP_DAMAGE_TYPES,
    ROL_OBJECT_TRAP_EFFECT_MASK,
    ROL_OBJECT_TRAP_EXTRA_BIT,
    ROL_OBJECT_TRAP_VALUE_OFFSET,
    SOURCE_APPLY_DAMROLL,
    SOURCE_APPLY_HITROLL,
    SOURCE_ARMOR_APPLY,
    SOURCE_INSTRUMENT_SUBTYPE_MAP,
    SOURCE_ITEM_TYPE_INSTRUMENT,
    SOURCE_SAVING_THROW_APPLIES,
    SOURCE_WEAPON_MESSAGE_MAP,
    SOURCE_WEAR_FINGER,
    SOURCE_WEAR_TAIL,
    SOURCE_WEAR_TAKE,
    TARGET_APPLY_AC_NEW,
    TARGET_ITEM_INSTRUMENT,
    TARGET_ITEM_PROF_BASIC,
    TARGET_ITEM_PROF_EXOTIC,
    TARGET_ITEM_PROF_MINIMAL,
    TARGET_ITEM_PROF_NONE,
    TARGET_MAX_ENHANCEMENT_BONUS,
    TARGET_MIN_ENHANCEMENT_BONUS,
    TARGET_WEAR_TAIL,
    TARGET_WEAR_TAKE,
    TARGET_WEAR_WIELD,
    WEAPON_FLAG_EXOTIC,
    WEAPON_FLAG_MARTIAL,
    WEAPON_FLAG_SIMPLE,
    _NON_CASTABLE_SOURCE_SPELLS,
    _SOURCE_INSTRUMENT_MAXIMUM_LEVEL,
    _SOURCE_LIQUID_MAP,
    _SOURCE_SPELL_MAP,
    _TARGET_INSTRUMENT_DEFAULT_BREAKABILITY,
    _TARGET_INSTRUMENT_MAX_DIFFICULTY_REDUCTION,
    _TARGET_INSTRUMENT_MAX_EFFECTIVENESS,
    _TARGET_INSTRUMENT_NAME_MAP,
    _TARGET_INSTRUMENT_SUBTYPE_NAMES,
    _TARGET_MAGIC_ITEM_TYPES,
    _TARGET_MAX_LIQUID,
    _TARGET_MAX_OBJECT_SPELL_LEVEL,
    _apply_missile_object,
    _apply_weapon_object,
    _convert_armor_apply_modifier,
    _instrument_subtype,
    _instrument_values,
    _object_enhancement_bonus,
    _object_target_type,
    _object_trap_values,
    _object_values,
    _unmapped,
    classify_source_tail_objects,
    emit_object,
)
from .rol_quests import _SOURCE_QUEST_REWARD_MAP, _bounded_tilde, _quest_command, emit_hlquest
from .rol_rooms import (
    ROL_ASTRAL_ROOM_FLAG,
    ROOM_FLAG_MAP,
    ROOM_TRANSFORMED_FLAGS,
    SECTOR_MAP,
    SOURCE_ASTRAL_SECTOR,
    ZONE_ROOM_FLAG_MAP,
    ZONE_SOURCE_ONLY_FLAGS,
    _exit_flags,
    _room_size_bits,
    emit_room,
)
from .rol_shops import (
    SHOP_CUSTOMER_BOUNDED_TOKENS,
    SHOP_CUSTOMER_TOKEN_MAP,
    SHOP_SOURCE_CUSTOMER_TOKENS,
    _shop_customer_restrictions,
    _shop_message,
    _shop_open_intervals,
    emit_shop,
)
from .rol_transform_common import (
    _SOURCE_COLOR,
    _TARGET_MAX_LEVEL,
    _directive_rows,
    _encoded,
    _mapped_bits,
    _source_mask_bits,
    _tilde,
    convert_text,
)
from .rol_zones import EQUIPMENT_POSITION_MAP, _emit_reset, _reset_probability, emit_zone

from .flags import encode_bits
from .rol_mob_calculator import (
    MobileCalculatorClient,
    calculation_to_dict,
    default_mobile_calculator,
)
from .rol_mobile_identity import load_mobile_conversion_policy, select_mobile_conversion
from .rol_conversion_types import RolRecord, normalize_identity
from .rol_weapon_mapping import (
    SOURCE_ITEM_TYPE_FIREWEAPON,
    SOURCE_ITEM_TYPE_MISSILE,
    SOURCE_ITEM_TYPE_QUIVER,
    SOURCE_ITEM_TYPE_WEAPON,
    SOURCE_QUIVER_THROWING,
    TARGET_ITEM_AMMO_POUCH,
    TARGET_ITEM_CONTAINER,
    TARGET_ITEM_MISSILE,
    TARGET_ITEM_WEAPON,
    WeaponInference,
    infer_ammunition,
    infer_ranged_weapon_type,
    infer_weapon_type,
    missile_break_probability,
)
from .rol_weapon_table import weapon_table
