-- Vessel System Phase 09: complete live-instance and schedule persistence.
-- Mirrors vessel_persistence_ensure_schema() in src/vessels_db.c.

CREATE TABLE IF NOT EXISTS ship_waypoints (
  waypoint_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(64) DEFAULT '',
  x FLOAT NOT NULL,
  y FLOAT NOT NULL,
  z FLOAT NOT NULL DEFAULT 0,
  tolerance FLOAT NOT NULL DEFAULT 5.0,
  wait_time INT NOT NULL DEFAULT 0,
  flags INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_waypoint_name (name),
  INDEX idx_waypoint_coords (x, y, z)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ship_routes (
  route_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(64) NOT NULL,
  loop_route TINYINT(1) NOT NULL DEFAULT 0,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_route_name (name),
  INDEX idx_route_active (active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ship_route_waypoints (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  route_id INT NOT NULL,
  waypoint_id INT NOT NULL,
  sequence_num INT NOT NULL,
  CONSTRAINT fk_ship_route_waypoint_route
    FOREIGN KEY (route_id) REFERENCES ship_routes(route_id) ON DELETE CASCADE,
  CONSTRAINT fk_ship_route_waypoint_waypoint
    FOREIGN KEY (waypoint_id) REFERENCES ship_waypoints(waypoint_id) ON DELETE CASCADE,
  UNIQUE KEY route_sequence (route_id, sequence_num),
  INDEX idx_route_waypoint (route_id, waypoint_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ship_runtime_state (
  ship_id INT NOT NULL PRIMARY KEY,
  instance_version INT NOT NULL DEFAULT 1,
  prototype_id INT NOT NULL DEFAULT 0,
  hull_object_vnum INT NOT NULL DEFAULT 70002,
  display_id CHAR(2) NOT NULL DEFAULT '',
  location_vnum INT NOT NULL DEFAULT 0,
  x FLOAT NOT NULL DEFAULT 0,
  y FLOAT NOT NULL DEFAULT 0,
  z FLOAT NOT NULL DEFAULT 0,
  dx FLOAT NOT NULL DEFAULT 0,
  dy FLOAT NOT NULL DEFAULT 0,
  dz FLOAT NOT NULL DEFAULT 0,
  heading SMALLINT NOT NULL DEFAULT 0,
  setheading SMALLINT NOT NULL DEFAULT 0,
  minspeed SMALLINT NOT NULL DEFAULT 0,
  maxspeed SMALLINT NOT NULL DEFAULT 0,
  speed SMALLINT NOT NULL DEFAULT 0,
  setspeed SMALLINT NOT NULL DEFAULT 0,
  dock_room INT NOT NULL DEFAULT 0,
  docked_to_ship INT NOT NULL DEFAULT -1,
  docking_room INT NOT NULL DEFAULT 0,
  max_docked_ships INT NOT NULL DEFAULT 0,
  maxfarmor TINYINT UNSIGNED NOT NULL DEFAULT 0,
  maxrarmor TINYINT UNSIGNED NOT NULL DEFAULT 0,
  maxparmor TINYINT UNSIGNED NOT NULL DEFAULT 0,
  maxsarmor TINYINT UNSIGNED NOT NULL DEFAULT 0,
  farmor TINYINT UNSIGNED NOT NULL DEFAULT 0,
  rarmor TINYINT UNSIGNED NOT NULL DEFAULT 0,
  parmor TINYINT UNSIGNED NOT NULL DEFAULT 0,
  sarmor TINYINT UNSIGNED NOT NULL DEFAULT 0,
  maxfinternal TINYINT UNSIGNED NOT NULL DEFAULT 0,
  maxrinternal TINYINT UNSIGNED NOT NULL DEFAULT 0,
  maxpinternal TINYINT UNSIGNED NOT NULL DEFAULT 0,
  maxsinternal TINYINT UNSIGNED NOT NULL DEFAULT 0,
  finternal TINYINT UNSIGNED NOT NULL DEFAULT 0,
  rinternal TINYINT UNSIGNED NOT NULL DEFAULT 0,
  pinternal TINYINT UNSIGNED NOT NULL DEFAULT 0,
  sinternal TINYINT UNSIGNED NOT NULL DEFAULT 0,
  maxturnrate TINYINT UNSIGNED NOT NULL DEFAULT 0,
  turnrate TINYINT UNSIGNED NOT NULL DEFAULT 0,
  maxmainsail TINYINT UNSIGNED NOT NULL DEFAULT 0,
  mainsail TINYINT UNSIGNED NOT NULL DEFAULT 0,
  hullweight TINYINT UNSIGNED NOT NULL DEFAULT 0,
  maxslots TINYINT UNSIGNED NOT NULL DEFAULT 0,
  last_attacker INT NOT NULL DEFAULT 0,
  wear_ticks INT NOT NULL DEFAULT 0,
  wage_ticks INT NOT NULL DEFAULT 0,
  room_types TEXT,
  slot_data LONGBLOB,
  autopilot_state INT NOT NULL DEFAULT 0,
  current_route_id INT NOT NULL DEFAULT 0,
  current_waypoint_index INT NOT NULL DEFAULT 0,
  autopilot_tick_counter INT NOT NULL DEFAULT 0,
  wait_remaining INT NOT NULL DEFAULT 0,
  last_update BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_ship_runtime_interior
    FOREIGN KEY (ship_id) REFERENCES ship_interiors(ship_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ship_schedules (
  schedule_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ship_id INT NOT NULL,
  route_id INT NOT NULL,
  interval_hours INT NOT NULL,
  next_departure INT NOT NULL DEFAULT 0,
  enabled TINYINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_ship_schedule (ship_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
